## Basic Configuration
baseurl = "https://shamun.dev/"
languageCode = "en-US"

title = "Ido Shamun"
theme = "custom-hyde"

## Hugo Built-in Features
 disqusShortname = "shamundev"
 googleAnalytics = "UA-141237878-1"
enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Ido Shamun"
    title = "Ido Shamun"
    # description = "..."
    authorimage = "/img/ido.jpeg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Ido Shamun"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "idoshamun"
    linkedin = "idoshamun"
    twitter = "idoshamun"
    email = "ido@shamun.dev"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"